//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnsUpdater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string GatewayPass {
            get {
                return ((string)(this["GatewayPass"]));
            }
            set {
                this["GatewayPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string GatewayUser {
            get {
                return ((string)(this["GatewayUser"]));
            }
            set {
                this["GatewayUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600000")]
        public int UpdateInterval {
            get {
                return ((int)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfDDNSEntry>
  <DDNSEntry>
    <Username>Jf7PFy6g7zDHgAWp</Username>
    <Password>pqYrZhfPnH8u8Eey</Password>
    <HostName>joelrevans.com</HostName>
  </DDNSEntry>
  <DDNSEntry>
    <Username>58x0ofYAbOpzx4N1</Username>
    <Password>oXMCZ0qCd7KN6oiQ</Password>
    <HostName>transit.joelrevans.com</HostName>
  </DDNSEntry>
</ArrayOfDDNSEntry>")]
        public global::DnsUpdater.DDNSEntry[] DDNSEntries {
            get {
                return ((global::DnsUpdater.DDNSEntry[])(this["DDNSEntries"]));
            }
            set {
                this["DDNSEntries"] = value;
            }
        }
    }
}
